### ISSUE TITLE
Error sentry

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/documentation#3]
(sentry)[root@felipeurrego ~]# sentry --config=/etc/sentry.conf.py start
Traceback (most recent call last):
  File "/var/www/sentry/bin/sentry", line 8, in <module>
    load_entry_point('sentry==5.4.5', 'console_scripts', 'sentry')()
  File "/var/www/sentry/lib/python2.6/site-packages/sentry-5.4.5-py2.6.egg/sentry/utils/runner.py", line 197, in main
    initializer=initialize_app,
  File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/runner.py", line 155, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/**init**.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/**init**.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/conf/__init__.py", line 93, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/importer.py", line 68, in load_module
    return self._load_module(fullname)
  File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/importer.py", line 92, in _load_module
    load_settings(self.config_path, allow_extras=self.allow_extras, settings=settings_mod)
  File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/settings.py", line 49, in load_settings
    execfile(mod_or_filename, conf.__dict__)
django.core.exceptions.ImproperlyConfigured: IndentationError('unexpected indent', ('/etc/sentry.conf.py', 58, 1, " SENTRY_URL_PREFIX = 'http://logs.felipeurrego.com'\n"))

**Comment by johnfelipe** [comment]
Hi, please help me, tnks

**Comment by pitbulk** [comment]
Sentry is an optional component to centralize your logs.
I think you really don't need it.

On the other hand, you must try to solve the problems yourself. Read the message error, is clear:

"django.core.exceptions.ImproperlyConfigured: IndentationError('unexpected indent', ('/etc/sentry.conf.py', 58, 1, " SENTRY_URL_PREFIX = 'http://logs.felipeurrego.com'\n"))

That line is wrong in your setting file.

**Comment by johnfelipe** [comment]
I changed and this is new bug:

```
    (sentry)[root@felipeurrego sentry]# sentry --config=/etc/sentry.conf.py start
    Traceback (most recent call last):
      File "/var/www/sentry/bin/sentry", line 8, in <module>
        load_entry_point('sentry==5.4.5', 'console_scripts', 'sentry')()
      File "/var/www/sentry/lib/python2.6/site-packages/sentry-5.4.5-py2.6.egg/sentry/utils/runner.py", line 197, in main
        initializer=initialize_app,
      File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/runner.py", line 155, in run_app
        management.execute_from_command_line([runner_name, command] + command_args)
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/__init__.py", line 443, in execute_from_command_line
        utility.execute()
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/__init__.py", line 382, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/__init__.py", line 252, in fetch_command
        app_name = get_commands()[subcommand]
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/management/__init__.py", line 101, in get_commands
        apps = settings.INSTALLED_APPS
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/utils/functional.py", line 184, in inner
        self._setup()
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/conf/__init__.py", line 42, in _setup
        self._wrapped = Settings(settings_module)
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/conf/__init__.py", line 93, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/var/www/sentry/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/utils/importlib.py", line 35, in import_module
        __import__(name)
      File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/importer.py", line 68, in load_module
        return self._load_module(fullname)
      File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/importer.py", line 95, in _load_module
        self.callback(settings_mod)
      File "/var/www/sentry/lib/python2.6/site-packages/logan-0.5.5-py2.6.egg/logan/runner.py", line 99, in settings_callback
        'settings': settings,
      File "/var/www/sentry/lib/python2.6/site-packages/sentry-5.4.5-py2.6.egg/sentry/utils/runner.py", line 171, in initialize_app
        from sentry.app import env
      File "/var/www/sentry/lib/python2.6/site-packages/sentry-5.4.5-py2.6.egg/sentry/app.py", line 25, in <module>
        buffer = get_instance(settings.BUFFER, settings.BUFFER_OPTIONS)
      File "/var/www/sentry/lib/python2.6/site-packages/sentry-5.4.5-py2.6.egg/sentry/app.py", line 20, in get_instance
        cls = import_string(path)
      File "/var/www/sentry/lib/python2.6/site-packages/sentry-5.4.5-py2.6.egg/sentry/utils/imports.py", line 40, in import_string
        raise ImportError(path)
    django.core.exceptions.ImproperlyConfigured: ImportError('sentry.buffer.Buffer',)
```
